version: "3"

services: 
    api:
        container_name: todo-host_api
        build:
            context: .
            dockerfile: Dockerfile

        depends_on: 
            - postgres

        environment: 
            POSTGRES_HOST: $POSTGRES_HOST
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_PORT: $POSTGRES_PORT
            POSTGRES_DB: $POSTGRES_DB
            API_PORT: $API_PORT

        ports: 
            - "$API_PORT:$API_PORT"

        networks: 
            - api_network

    postgres:
        container_name: todo-host_postgres
        image: postgres
        ports:
            - "$POSTGRES_PORT:$POSTGRES_PORT"

        environment: 
            # - POSTGRES_USER=$POSTGRES_USER
            # - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            # - POSTGRES_DB=$POSTGRES_DB
            POSTGRES_USER: $POSTGRES_USER 
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB

        networks: 
            - api_network
        
        volumes: 
            - $HOME/docker/volumes/postgres:/var/lib/postgresql/data

networks: 
    api_network: